name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Debug info
        run: |
          echo "🔎 Repository: $GITHUB_REPOSITORY"
          echo "🔎 Branch: $GITHUB_REF"

      - name: Verify Azure Token and Project Structure
        run: |
          echo "🔐 Checking token..."
          if [ -z "$AZURE_TOKEN" ]; then
            echo "❌ ERROR: Azure token not found"
            exit 1
          fi
          echo "✅ Token present (${#AZURE_TOKEN} chars)"
          echo "✅ Token preview: ${AZURE_TOKEN:0:6}...${AZURE_TOKEN: -6}"

          echo "📁 Checking project structure..."
          if [ -f "package.json" ]; then
            echo "✅ package.json found"
          else
            echo "❌ package.json not found"
            exit 1
          fi

          if grep -q '"build".*"vite build"' package.json; then
            echo "✅ Vite build script found"
          else
            echo "❌ Build script not found or incorrect"
            exit 1
          fi
        env:
          AZURE_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_OCEAN_0E2A3DE0F }}

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to Azure Static Web App
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_OCEAN_0E2A3DE0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"           # raíz del proyecto
          output_location: "dist"     # carpeta generada por Vite
          app_build_command: "npm run build"
          skip_api_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job

    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_OCEAN_0E2A3DE0F }}
          action: "close"
